### ISSUE TITLE
Incompatibility / deprecation of dependencies

### ISSUE THREAD

**Issue by pocvirk** [pjcigan/obsplanning#2]
This module looks very nice.
I can not complete the tutorials however.
I am trying to run the following cell:

import numpy as np
import ephem
import datetime as dt
from astropy.time import Time
import pytz
import matplotlib.pyplot as plt

import obsplanning as obs

wht = obs.create_ephem_observer('WHT', '-17 52 53.8', '28 45 37.7', 2344)
crab = obs.create_ephem_target('Crab Nebula','05:34:31.94','22:00:52.2')

# Observation start/end times:  5 PM to 9 AM local time
sunset, twi_civil, twi_naut, twi_astro = obs.calculate_twilight_times(wht,
    '2025/01/01 23:59:00')
obsstart_local_dt = obs.dt_naive_to_dt_aware(
    ephem.Date('2025/10/31 17:00:00').datetime(), 'Atlantic/Canary' )
obsend_local_dt = obs.dt_naive_to_dt_aware(
    ephem.Date('2025/11/01 09:00:00').datetime(), 'Atlantic/Canary' )
obsstart = obs.dtaware_to_ephem(obsstart_local_dt)
obsend   = obs.dtaware_to_ephem(obsend_local_dt)

# A couple more example targets
ngc1052=obs.create_ephem_target('NGC1052','02:41:04.7985','-08:15:20.751')
ngc3147=obs.create_ephem_target('NGC3147','10:16:53.65','73:24:02.7')

But Im getting the folllowing warning:
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multicolorfits.py:39: FutureWarning: The traitsui.qt4.* modules have moved to traitsui.qt.*.

Applications which require backwards compatibility can either:

- set the ETS_QT4_IMPORTS environment variable
- set the ETS_TOOLKIT environment variable to "qt4",
- the ETSConfig.toolkit to "qt4"
- install a ShadowedModuleFinder into sys.meta_path::

    import sys
    from pyface.ui import ShadowedModuleFinder

    sys.meta_path.append(ShadowedModuleFinder(
        package="traitsui.qt4.",
        true_package="traitsui.qt.",
    ))

  from traitsui.qt4.editor import Editor

and error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multicolorfits.py in <module>
     38     from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT
---> 39     from traitsui.qt4.editor import Editor
     40     try:

ModuleNotFoundError: No module named 'traitsui.qt4.editor'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-4087777f76b9> in <module>
      6 import matplotlib.pyplot as plt
      7 
----> 8 import obsplanning as obs
      9 
     10 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/obsplanning.py in <module>
     60 from astropy.wcs import WCS
     61 import astropy.units as u
---> 62 import multicolorfits as mcf
     63 from matplotlib import rcParams
     64 import matplotlib.patches as patches

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/multicolorfits.py in <module>
     49 except:
     50     ### PyQt4
---> 51     matplotlib.use('Qt4Agg')
     52     from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
     53     from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/__init__.py in use(backend, force)
   1138     matplotlib.get_backend
   1139     """
-> 1140     name = validate_backend(backend)
   1141     # don't (prematurely) resolve the "auto" backend setting
   1142     if rcParams._get_backend_or_none() == name:

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/rcsetup.py in validate_backend(s)
    253     backend = (
    254         s if s is _auto_backend_sentinel or s.startswith("module://")
--> 255         else _validate_standard_backends(s))
    256     return backend
    257 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/rcsetup.py in __call__(self, s)
     80                 and s[1:-1] in self.valid):
     81             msg += "; remove quotes surrounding your string"
---> 82         raise ValueError(msg)
     83 
     84 

ValueError: 'qt4agg' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg', 'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

it seems the qt4agg backend is not supported any more.

**Comment by pjcigan** [comment]
Hello, 

This was an issue with dependency package multicolorfits attempting to import pyqt5 or pyqt4, but that has now been updated to use pyqt6 by default.  
Regardless, the latest version of obsplanning has been changed to make multicolorfits an 'extras' package instead of a 'required' one (it's currently only used here for making finder plots).
